apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: general-project
  namespace: argocd
spec:
  # Project description
  description: general project

  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - git@github.com:Lisa-Stats/express-app-helm-charts.git

  # Destination clusters can be identified by 'server', 'name', or both.
  destinations:
    # test destinations
    - namespace: testing
      server: https://kubernetes.default.svc
    - namespace: ingress-nginx
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc

  # Allow all cluster-scoped resources
  # TODO - update this
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange
    - group: ''
      kind: NetworkPolicy

  # Deny all namespaced-scoped resources from being created, except for Deployment and StatefulSet
  # namespaceResourceWhitelist:
  # - group: 'apps'
  #   kind: Deployment
  # - group: 'apps'
  #   kind: StatefulSet

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false

  roles:
  # A role which provides read-only access to all applications in the project
    # - name: guest
    #   description: Read-only privileges to my-project
    #   policies:
    #     - p, proj:my-project:read-only, applications, get, my-project/*, allow
    #   groups:
    #     - my-oidc-group

  # # A role which provides sync privileges to a CI system
  # - name: ci-role
  #   description: Sync privileges for guestbook-dev
  #   policies:
  #   - p, proj:my-project:ci-role, applications, sync, my-project/guestbook-dev, allow
